package airport_01Jsf.utils;

public enum NavigationMapper {

	HOME_PAGE
	, LOGIN_SUBPAGE
	, RESERVATION_SUBPAGE
	, USER_AREA_RESERVATIONS_SUBPAGE
	, USER_AREA_UNSUBSCRIBE_SUBPAGE
	, REGISTRATION_SUBPAGE
	, ADMIN_HOME_PAGE
	, ADMIN_FLEET_SUBPAGE
	, ADMIN_AIRPORTS_SUBPAGE
	, ERROR_PAGE
	, SEARCH_SUBPAGE;
	
	
	NavigationMapper() {
	}
	
}
